// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: faas/v1/function.proto

package faasv1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FunctionPhase describes the high-level lifecycle state of a function as
// observed by the reconciler.
type FunctionPhase int32

const (
	FunctionPhase_FUNCTION_PHASE_UNSPECIFIED FunctionPhase = 0
	FunctionPhase_FUNCTION_PHASE_PENDING     FunctionPhase = 1
	FunctionPhase_FUNCTION_PHASE_READY       FunctionPhase = 2
	FunctionPhase_FUNCTION_PHASE_DEGRADED    FunctionPhase = 3
	FunctionPhase_FUNCTION_PHASE_DELETING    FunctionPhase = 4
	FunctionPhase_FUNCTION_PHASE_FAILED      FunctionPhase = 5
)

// Enum value maps for FunctionPhase.
var (
	FunctionPhase_name = map[int32]string{
		0: "FUNCTION_PHASE_UNSPECIFIED",
		1: "FUNCTION_PHASE_PENDING",
		2: "FUNCTION_PHASE_READY",
		3: "FUNCTION_PHASE_DEGRADED",
		4: "FUNCTION_PHASE_DELETING",
		5: "FUNCTION_PHASE_FAILED",
	}
	FunctionPhase_value = map[string]int32{
		"FUNCTION_PHASE_UNSPECIFIED": 0,
		"FUNCTION_PHASE_PENDING":     1,
		"FUNCTION_PHASE_READY":       2,
		"FUNCTION_PHASE_DEGRADED":    3,
		"FUNCTION_PHASE_DELETING":    4,
		"FUNCTION_PHASE_FAILED":      5,
	}
)

func (x FunctionPhase) Enum() *FunctionPhase {
	p := new(FunctionPhase)
	*p = x
	return p
}

func (x FunctionPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FunctionPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_faas_v1_function_proto_enumTypes[0].Descriptor()
}

func (FunctionPhase) Type() protoreflect.EnumType {
	return &file_faas_v1_function_proto_enumTypes[0]
}

func (x FunctionPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FunctionPhase.Descriptor instead.
func (FunctionPhase) EnumDescriptor() ([]byte, []int) {
	return file_faas_v1_function_proto_rawDescGZIP(), []int{0}
}

// FunctionStatus is the observed state of a function. It is set by the
// reconciler and is read-only from a client perspective.
type FunctionStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phase         FunctionPhase          `protobuf:"varint,1,opt,name=phase,proto3,enum=faas.v1.FunctionPhase" json:"phase,omitempty"`
	ReadyReplicas int32                  `protobuf:"varint,2,opt,name=ready_replicas,json=readyReplicas,proto3" json:"ready_replicas,omitempty"`
	// observed_version is the spec version the reconciler has reacted to.
	ObservedVersion int64 `protobuf:"varint,3,opt,name=observed_version,json=observedVersion,proto3" json:"observed_version,omitempty"`
	// message is a human-readable explanation of the current phase, primarily
	// used when phase is DEGRADED or FAILED.
	Message            string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	LastTransitionTime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_transition_time,json=lastTransitionTime,proto3" json:"last_transition_time,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *FunctionStatus) Reset() {
	*x = FunctionStatus{}
	mi := &file_faas_v1_function_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionStatus) ProtoMessage() {}

func (x *FunctionStatus) ProtoReflect() protoreflect.Message {
	mi := &file_faas_v1_function_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionStatus.ProtoReflect.Descriptor instead.
func (*FunctionStatus) Descriptor() ([]byte, []int) {
	return file_faas_v1_function_proto_rawDescGZIP(), []int{0}
}

func (x *FunctionStatus) GetPhase() FunctionPhase {
	if x != nil {
		return x.Phase
	}
	return FunctionPhase_FUNCTION_PHASE_UNSPECIFIED
}

func (x *FunctionStatus) GetReadyReplicas() int32 {
	if x != nil {
		return x.ReadyReplicas
	}
	return 0
}

func (x *FunctionStatus) GetObservedVersion() int64 {
	if x != nil {
		return x.ObservedVersion
	}
	return 0
}

func (x *FunctionStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FunctionStatus) GetLastTransitionTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastTransitionTime
	}
	return nil
}

// Function describes a user function deployed on the platform.
type Function struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name uniquely identifies the function within the platform. It MUST match
	// DNS-1123 label rules so it can be used as a Kubernetes resource name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// image is a fully-qualified OCI image reference the platform will deploy.
	Image string `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	// replicas is the desired number of pods serving this function.
	Replicas int32 `protobuf:"varint,3,opt,name=replicas,proto3" json:"replicas,omitempty"`
	// env is a flat key/value map of environment variables to inject into the
	// function's pod template.
	Env map[string]string `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// version is monotonically incremented by the control-plane on each spec
	// mutation. It is filled by the server.
	Version   int64                  `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// status is the observed state of the function.
	Status        *FunctionStatus `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Function) Reset() {
	*x = Function{}
	mi := &file_faas_v1_function_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Function) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Function) ProtoMessage() {}

func (x *Function) ProtoReflect() protoreflect.Message {
	mi := &file_faas_v1_function_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Function.ProtoReflect.Descriptor instead.
func (*Function) Descriptor() ([]byte, []int) {
	return file_faas_v1_function_proto_rawDescGZIP(), []int{1}
}

func (x *Function) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Function) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Function) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

func (x *Function) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *Function) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Function) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Function) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Function) GetStatus() *FunctionStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type CreateFunctionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// function holds the desired spec. Output-only fields are ignored.
	Function      *Function `protobuf:"bytes,1,opt,name=function,proto3" json:"function,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFunctionRequest) Reset() {
	*x = CreateFunctionRequest{}
	mi := &file_faas_v1_function_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFunctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFunctionRequest) ProtoMessage() {}

func (x *CreateFunctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_faas_v1_function_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFunctionRequest.ProtoReflect.Descriptor instead.
func (*CreateFunctionRequest) Descriptor() ([]byte, []int) {
	return file_faas_v1_function_proto_rawDescGZIP(), []int{2}
}

func (x *CreateFunctionRequest) GetFunction() *Function {
	if x != nil {
		return x.Function
	}
	return nil
}

type CreateFunctionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Function      *Function              `protobuf:"bytes,1,opt,name=function,proto3" json:"function,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFunctionResponse) Reset() {
	*x = CreateFunctionResponse{}
	mi := &file_faas_v1_function_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFunctionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFunctionResponse) ProtoMessage() {}

func (x *CreateFunctionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_faas_v1_function_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFunctionResponse.ProtoReflect.Descriptor instead.
func (*CreateFunctionResponse) Descriptor() ([]byte, []int) {
	return file_faas_v1_function_proto_rawDescGZIP(), []int{3}
}

func (x *CreateFunctionResponse) GetFunction() *Function {
	if x != nil {
		return x.Function
	}
	return nil
}

type GetFunctionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFunctionRequest) Reset() {
	*x = GetFunctionRequest{}
	mi := &file_faas_v1_function_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFunctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFunctionRequest) ProtoMessage() {}

func (x *GetFunctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_faas_v1_function_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFunctionRequest.ProtoReflect.Descriptor instead.
func (*GetFunctionRequest) Descriptor() ([]byte, []int) {
	return file_faas_v1_function_proto_rawDescGZIP(), []int{4}
}

func (x *GetFunctionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetFunctionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Function      *Function              `protobuf:"bytes,1,opt,name=function,proto3" json:"function,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFunctionResponse) Reset() {
	*x = GetFunctionResponse{}
	mi := &file_faas_v1_function_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFunctionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFunctionResponse) ProtoMessage() {}

func (x *GetFunctionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_faas_v1_function_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFunctionResponse.ProtoReflect.Descriptor instead.
func (*GetFunctionResponse) Descriptor() ([]byte, []int) {
	return file_faas_v1_function_proto_rawDescGZIP(), []int{5}
}

func (x *GetFunctionResponse) GetFunction() *Function {
	if x != nil {
		return x.Function
	}
	return nil
}

type ListFunctionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// page_size is a hint; the server may return fewer items.
	PageSize      int32  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFunctionsRequest) Reset() {
	*x = ListFunctionsRequest{}
	mi := &file_faas_v1_function_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFunctionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFunctionsRequest) ProtoMessage() {}

func (x *ListFunctionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_faas_v1_function_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFunctionsRequest.ProtoReflect.Descriptor instead.
func (*ListFunctionsRequest) Descriptor() ([]byte, []int) {
	return file_faas_v1_function_proto_rawDescGZIP(), []int{6}
}

func (x *ListFunctionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListFunctionsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListFunctionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Functions     []*Function            `protobuf:"bytes,1,rep,name=functions,proto3" json:"functions,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFunctionsResponse) Reset() {
	*x = ListFunctionsResponse{}
	mi := &file_faas_v1_function_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFunctionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFunctionsResponse) ProtoMessage() {}

func (x *ListFunctionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_faas_v1_function_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFunctionsResponse.ProtoReflect.Descriptor instead.
func (*ListFunctionsResponse) Descriptor() ([]byte, []int) {
	return file_faas_v1_function_proto_rawDescGZIP(), []int{7}
}

func (x *ListFunctionsResponse) GetFunctions() []*Function {
	if x != nil {
		return x.Functions
	}
	return nil
}

func (x *ListFunctionsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type UpdateFunctionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// function carries the new desired state; function.name selects the target.
	Function *Function `protobuf:"bytes,1,opt,name=function,proto3" json:"function,omitempty"`
	// update_mask restricts which fields of function are applied. When empty,
	// all mutable fields are replaced.
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFunctionRequest) Reset() {
	*x = UpdateFunctionRequest{}
	mi := &file_faas_v1_function_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFunctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFunctionRequest) ProtoMessage() {}

func (x *UpdateFunctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_faas_v1_function_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFunctionRequest.ProtoReflect.Descriptor instead.
func (*UpdateFunctionRequest) Descriptor() ([]byte, []int) {
	return file_faas_v1_function_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateFunctionRequest) GetFunction() *Function {
	if x != nil {
		return x.Function
	}
	return nil
}

func (x *UpdateFunctionRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type UpdateFunctionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Function      *Function              `protobuf:"bytes,1,opt,name=function,proto3" json:"function,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFunctionResponse) Reset() {
	*x = UpdateFunctionResponse{}
	mi := &file_faas_v1_function_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFunctionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFunctionResponse) ProtoMessage() {}

func (x *UpdateFunctionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_faas_v1_function_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFunctionResponse.ProtoReflect.Descriptor instead.
func (*UpdateFunctionResponse) Descriptor() ([]byte, []int) {
	return file_faas_v1_function_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateFunctionResponse) GetFunction() *Function {
	if x != nil {
		return x.Function
	}
	return nil
}

type DeleteFunctionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFunctionRequest) Reset() {
	*x = DeleteFunctionRequest{}
	mi := &file_faas_v1_function_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFunctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFunctionRequest) ProtoMessage() {}

func (x *DeleteFunctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_faas_v1_function_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFunctionRequest.ProtoReflect.Descriptor instead.
func (*DeleteFunctionRequest) Descriptor() ([]byte, []int) {
	return file_faas_v1_function_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteFunctionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteFunctionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFunctionResponse) Reset() {
	*x = DeleteFunctionResponse{}
	mi := &file_faas_v1_function_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFunctionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFunctionResponse) ProtoMessage() {}

func (x *DeleteFunctionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_faas_v1_function_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFunctionResponse.ProtoReflect.Descriptor instead.
func (*DeleteFunctionResponse) Descriptor() ([]byte, []int) {
	return file_faas_v1_function_proto_rawDescGZIP(), []int{11}
}

type GetFunctionLogsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// follow keeps the stream open and pushes new log lines as they arrive.
	Follow bool `protobuf:"varint,2,opt,name=follow,proto3" json:"follow,omitempty"`
	// tail_lines, if positive, limits the initial backfill from the most recent
	// log lines.
	TailLines int32 `protobuf:"varint,3,opt,name=tail_lines,json=tailLines,proto3" json:"tail_lines,omitempty"`
	// since, when set, filters out log lines emitted before this timestamp.
	Since         *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=since,proto3" json:"since,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFunctionLogsRequest) Reset() {
	*x = GetFunctionLogsRequest{}
	mi := &file_faas_v1_function_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFunctionLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFunctionLogsRequest) ProtoMessage() {}

func (x *GetFunctionLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_faas_v1_function_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFunctionLogsRequest.ProtoReflect.Descriptor instead.
func (*GetFunctionLogsRequest) Descriptor() ([]byte, []int) {
	return file_faas_v1_function_proto_rawDescGZIP(), []int{12}
}

func (x *GetFunctionLogsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetFunctionLogsRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

func (x *GetFunctionLogsRequest) GetTailLines() int32 {
	if x != nil {
		return x.TailLines
	}
	return 0
}

func (x *GetFunctionLogsRequest) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

type LogEntry struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// pod is the name of the pod the line was read from.
	Pod string `protobuf:"bytes,2,opt,name=pod,proto3" json:"pod,omitempty"`
	// line is the raw log line (without trailing newline).
	Line          string `protobuf:"bytes,3,opt,name=line,proto3" json:"line,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_faas_v1_function_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_faas_v1_function_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_faas_v1_function_proto_rawDescGZIP(), []int{13}
}

func (x *LogEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *LogEntry) GetPod() string {
	if x != nil {
		return x.Pod
	}
	return ""
}

func (x *LogEntry) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

var File_faas_v1_function_proto protoreflect.FileDescriptor

const file_faas_v1_function_proto_rawDesc = "" +
	"\n" +
	"\x16faas/v1/function.proto\x12\afaas.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xf8\x01\n" +
	"\x0eFunctionStatus\x12,\n" +
	"\x05phase\x18\x01 \x01(\x0e2\x16.faas.v1.FunctionPhaseR\x05phase\x12%\n" +
	"\x0eready_replicas\x18\x02 \x01(\x05R\rreadyReplicas\x12)\n" +
	"\x10observed_version\x18\x03 \x01(\x03R\x0fobservedVersion\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12L\n" +
	"\x14last_transition_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x12lastTransitionTime\"\x95\x03\n" +
	"\bFunction\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x02R\x04name\x12\x19\n" +
	"\x05image\x18\x02 \x01(\tB\x03\xe0A\x02R\x05image\x12\x1a\n" +
	"\breplicas\x18\x03 \x01(\x05R\breplicas\x12,\n" +
	"\x03env\x18\x04 \x03(\v2\x1a.faas.v1.Function.EnvEntryR\x03env\x12\x1d\n" +
	"\aversion\x18\x05 \x01(\x03B\x03\xe0A\x03R\aversion\x12>\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\tcreatedAt\x12>\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\tupdatedAt\x124\n" +
	"\x06status\x18\b \x01(\v2\x17.faas.v1.FunctionStatusB\x03\xe0A\x03R\x06status\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"K\n" +
	"\x15CreateFunctionRequest\x122\n" +
	"\bfunction\x18\x01 \x01(\v2\x11.faas.v1.FunctionB\x03\xe0A\x02R\bfunction\"G\n" +
	"\x16CreateFunctionResponse\x12-\n" +
	"\bfunction\x18\x01 \x01(\v2\x11.faas.v1.FunctionR\bfunction\"-\n" +
	"\x12GetFunctionRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x02R\x04name\"D\n" +
	"\x13GetFunctionResponse\x12-\n" +
	"\bfunction\x18\x01 \x01(\v2\x11.faas.v1.FunctionR\bfunction\"R\n" +
	"\x14ListFunctionsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"p\n" +
	"\x15ListFunctionsResponse\x12/\n" +
	"\tfunctions\x18\x01 \x03(\v2\x11.faas.v1.FunctionR\tfunctions\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\x88\x01\n" +
	"\x15UpdateFunctionRequest\x122\n" +
	"\bfunction\x18\x01 \x01(\v2\x11.faas.v1.FunctionB\x03\xe0A\x02R\bfunction\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"G\n" +
	"\x16UpdateFunctionResponse\x12-\n" +
	"\bfunction\x18\x01 \x01(\v2\x11.faas.v1.FunctionR\bfunction\"0\n" +
	"\x15DeleteFunctionRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x02R\x04name\"\x18\n" +
	"\x16DeleteFunctionResponse\"\x9a\x01\n" +
	"\x16GetFunctionLogsRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x02R\x04name\x12\x16\n" +
	"\x06follow\x18\x02 \x01(\bR\x06follow\x12\x1d\n" +
	"\n" +
	"tail_lines\x18\x03 \x01(\x05R\ttailLines\x120\n" +
	"\x05since\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x05since\"j\n" +
	"\bLogEntry\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x10\n" +
	"\x03pod\x18\x02 \x01(\tR\x03pod\x12\x12\n" +
	"\x04line\x18\x03 \x01(\tR\x04line*\xba\x01\n" +
	"\rFunctionPhase\x12\x1e\n" +
	"\x1aFUNCTION_PHASE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16FUNCTION_PHASE_PENDING\x10\x01\x12\x18\n" +
	"\x14FUNCTION_PHASE_READY\x10\x02\x12\x1b\n" +
	"\x17FUNCTION_PHASE_DEGRADED\x10\x03\x12\x1b\n" +
	"\x17FUNCTION_PHASE_DELETING\x10\x04\x12\x19\n" +
	"\x15FUNCTION_PHASE_FAILED\x10\x052\x84\x05\n" +
	"\x0fFunctionService\x12j\n" +
	"\x06Create\x12\x1e.faas.v1.CreateFunctionRequest\x1a\x1f.faas.v1.CreateFunctionResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\bfunction\"\r/v1/functions\x12^\n" +
	"\x03Get\x12\x1b.faas.v1.GetFunctionRequest\x1a\x1c.faas.v1.GetFunctionResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/functions/{name}\x12\\\n" +
	"\x04List\x12\x1d.faas.v1.ListFunctionsRequest\x1a\x1e.faas.v1.ListFunctionsResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/functions\x12z\n" +
	"\x06Update\x12\x1e.faas.v1.UpdateFunctionRequest\x1a\x1f.faas.v1.UpdateFunctionResponse\"/\x82\xd3\xe4\x93\x02):\bfunction2\x1d/v1/functions/{function.name}\x12g\n" +
	"\x06Delete\x12\x1e.faas.v1.DeleteFunctionRequest\x1a\x1f.faas.v1.DeleteFunctionResponse\"\x1c\x82\xd3\xe4\x93\x02\x16*\x14/v1/functions/{name}\x12b\n" +
	"\aGetLogs\x12\x1f.faas.v1.GetFunctionLogsRequest\x1a\x11.faas.v1.LogEntry\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/functions/{name}/logs0\x01B\x8c\x02\x92A\x7f\x12V\n" +
	"\x10FaaS Control API\x12>Control-plane API for managing functions on the FaaS platform.2\x02v1*\x01\x012\x10application/json:\x10application/json\n" +
	"\vcom.faas.v1B\rFunctionProtoP\x01Z/github.com/uniqelus/faas/pkg/api/faas/v1;faasv1\xa2\x02\x03FXX\xaa\x02\aFaas.V1\xca\x02\aFaas\\V1\xe2\x02\x13Faas\\V1\\GPBMetadata\xea\x02\bFaas::V1b\x06proto3"

var (
	file_faas_v1_function_proto_rawDescOnce sync.Once
	file_faas_v1_function_proto_rawDescData []byte
)

func file_faas_v1_function_proto_rawDescGZIP() []byte {
	file_faas_v1_function_proto_rawDescOnce.Do(func() {
		file_faas_v1_function_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_faas_v1_function_proto_rawDesc), len(file_faas_v1_function_proto_rawDesc)))
	})
	return file_faas_v1_function_proto_rawDescData
}

var file_faas_v1_function_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_faas_v1_function_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_faas_v1_function_proto_goTypes = []any{
	(FunctionPhase)(0),             // 0: faas.v1.FunctionPhase
	(*FunctionStatus)(nil),         // 1: faas.v1.FunctionStatus
	(*Function)(nil),               // 2: faas.v1.Function
	(*CreateFunctionRequest)(nil),  // 3: faas.v1.CreateFunctionRequest
	(*CreateFunctionResponse)(nil), // 4: faas.v1.CreateFunctionResponse
	(*GetFunctionRequest)(nil),     // 5: faas.v1.GetFunctionRequest
	(*GetFunctionResponse)(nil),    // 6: faas.v1.GetFunctionResponse
	(*ListFunctionsRequest)(nil),   // 7: faas.v1.ListFunctionsRequest
	(*ListFunctionsResponse)(nil),  // 8: faas.v1.ListFunctionsResponse
	(*UpdateFunctionRequest)(nil),  // 9: faas.v1.UpdateFunctionRequest
	(*UpdateFunctionResponse)(nil), // 10: faas.v1.UpdateFunctionResponse
	(*DeleteFunctionRequest)(nil),  // 11: faas.v1.DeleteFunctionRequest
	(*DeleteFunctionResponse)(nil), // 12: faas.v1.DeleteFunctionResponse
	(*GetFunctionLogsRequest)(nil), // 13: faas.v1.GetFunctionLogsRequest
	(*LogEntry)(nil),               // 14: faas.v1.LogEntry
	nil,                            // 15: faas.v1.Function.EnvEntry
	(*timestamppb.Timestamp)(nil),  // 16: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil),  // 17: google.protobuf.FieldMask
}
var file_faas_v1_function_proto_depIdxs = []int32{
	0,  // 0: faas.v1.FunctionStatus.phase:type_name -> faas.v1.FunctionPhase
	16, // 1: faas.v1.FunctionStatus.last_transition_time:type_name -> google.protobuf.Timestamp
	15, // 2: faas.v1.Function.env:type_name -> faas.v1.Function.EnvEntry
	16, // 3: faas.v1.Function.created_at:type_name -> google.protobuf.Timestamp
	16, // 4: faas.v1.Function.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 5: faas.v1.Function.status:type_name -> faas.v1.FunctionStatus
	2,  // 6: faas.v1.CreateFunctionRequest.function:type_name -> faas.v1.Function
	2,  // 7: faas.v1.CreateFunctionResponse.function:type_name -> faas.v1.Function
	2,  // 8: faas.v1.GetFunctionResponse.function:type_name -> faas.v1.Function
	2,  // 9: faas.v1.ListFunctionsResponse.functions:type_name -> faas.v1.Function
	2,  // 10: faas.v1.UpdateFunctionRequest.function:type_name -> faas.v1.Function
	17, // 11: faas.v1.UpdateFunctionRequest.update_mask:type_name -> google.protobuf.FieldMask
	2,  // 12: faas.v1.UpdateFunctionResponse.function:type_name -> faas.v1.Function
	16, // 13: faas.v1.GetFunctionLogsRequest.since:type_name -> google.protobuf.Timestamp
	16, // 14: faas.v1.LogEntry.timestamp:type_name -> google.protobuf.Timestamp
	3,  // 15: faas.v1.FunctionService.Create:input_type -> faas.v1.CreateFunctionRequest
	5,  // 16: faas.v1.FunctionService.Get:input_type -> faas.v1.GetFunctionRequest
	7,  // 17: faas.v1.FunctionService.List:input_type -> faas.v1.ListFunctionsRequest
	9,  // 18: faas.v1.FunctionService.Update:input_type -> faas.v1.UpdateFunctionRequest
	11, // 19: faas.v1.FunctionService.Delete:input_type -> faas.v1.DeleteFunctionRequest
	13, // 20: faas.v1.FunctionService.GetLogs:input_type -> faas.v1.GetFunctionLogsRequest
	4,  // 21: faas.v1.FunctionService.Create:output_type -> faas.v1.CreateFunctionResponse
	6,  // 22: faas.v1.FunctionService.Get:output_type -> faas.v1.GetFunctionResponse
	8,  // 23: faas.v1.FunctionService.List:output_type -> faas.v1.ListFunctionsResponse
	10, // 24: faas.v1.FunctionService.Update:output_type -> faas.v1.UpdateFunctionResponse
	12, // 25: faas.v1.FunctionService.Delete:output_type -> faas.v1.DeleteFunctionResponse
	14, // 26: faas.v1.FunctionService.GetLogs:output_type -> faas.v1.LogEntry
	21, // [21:27] is the sub-list for method output_type
	15, // [15:21] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_faas_v1_function_proto_init() }
func file_faas_v1_function_proto_init() {
	if File_faas_v1_function_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_faas_v1_function_proto_rawDesc), len(file_faas_v1_function_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_faas_v1_function_proto_goTypes,
		DependencyIndexes: file_faas_v1_function_proto_depIdxs,
		EnumInfos:         file_faas_v1_function_proto_enumTypes,
		MessageInfos:      file_faas_v1_function_proto_msgTypes,
	}.Build()
	File_faas_v1_function_proto = out.File
	file_faas_v1_function_proto_goTypes = nil
	file_faas_v1_function_proto_depIdxs = nil
}
