// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package faasv1

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc"
	"google.golang.org/grpc/metadata"
)

// NewMockFunctionServiceClient creates a new instance of MockFunctionServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFunctionServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFunctionServiceClient {
	mock := &MockFunctionServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFunctionServiceClient is an autogenerated mock type for the FunctionServiceClient type
type MockFunctionServiceClient struct {
	mock.Mock
}

type MockFunctionServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFunctionServiceClient) EXPECT() *MockFunctionServiceClient_Expecter {
	return &MockFunctionServiceClient_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockFunctionServiceClient
func (_mock *MockFunctionServiceClient) Create(ctx context.Context, in *CreateFunctionRequest, opts ...grpc.CallOption) (*CreateFunctionResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *CreateFunctionResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *CreateFunctionRequest, ...grpc.CallOption) (*CreateFunctionResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *CreateFunctionRequest, ...grpc.CallOption) *CreateFunctionResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*CreateFunctionResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *CreateFunctionRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFunctionServiceClient_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockFunctionServiceClient_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - in *CreateFunctionRequest
//   - opts ...grpc.CallOption
func (_e *MockFunctionServiceClient_Expecter) Create(ctx interface{}, in interface{}, opts ...interface{}) *MockFunctionServiceClient_Create_Call {
	return &MockFunctionServiceClient_Create_Call{Call: _e.mock.On("Create",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockFunctionServiceClient_Create_Call) Run(run func(ctx context.Context, in *CreateFunctionRequest, opts ...grpc.CallOption)) *MockFunctionServiceClient_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *CreateFunctionRequest
		if args[1] != nil {
			arg1 = args[1].(*CreateFunctionRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockFunctionServiceClient_Create_Call) Return(createFunctionResponse *CreateFunctionResponse, err error) *MockFunctionServiceClient_Create_Call {
	_c.Call.Return(createFunctionResponse, err)
	return _c
}

func (_c *MockFunctionServiceClient_Create_Call) RunAndReturn(run func(ctx context.Context, in *CreateFunctionRequest, opts ...grpc.CallOption) (*CreateFunctionResponse, error)) *MockFunctionServiceClient_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockFunctionServiceClient
func (_mock *MockFunctionServiceClient) Delete(ctx context.Context, in *DeleteFunctionRequest, opts ...grpc.CallOption) (*DeleteFunctionResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *DeleteFunctionResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *DeleteFunctionRequest, ...grpc.CallOption) (*DeleteFunctionResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *DeleteFunctionRequest, ...grpc.CallOption) *DeleteFunctionResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*DeleteFunctionResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *DeleteFunctionRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFunctionServiceClient_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockFunctionServiceClient_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - in *DeleteFunctionRequest
//   - opts ...grpc.CallOption
func (_e *MockFunctionServiceClient_Expecter) Delete(ctx interface{}, in interface{}, opts ...interface{}) *MockFunctionServiceClient_Delete_Call {
	return &MockFunctionServiceClient_Delete_Call{Call: _e.mock.On("Delete",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockFunctionServiceClient_Delete_Call) Run(run func(ctx context.Context, in *DeleteFunctionRequest, opts ...grpc.CallOption)) *MockFunctionServiceClient_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *DeleteFunctionRequest
		if args[1] != nil {
			arg1 = args[1].(*DeleteFunctionRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockFunctionServiceClient_Delete_Call) Return(deleteFunctionResponse *DeleteFunctionResponse, err error) *MockFunctionServiceClient_Delete_Call {
	_c.Call.Return(deleteFunctionResponse, err)
	return _c
}

func (_c *MockFunctionServiceClient_Delete_Call) RunAndReturn(run func(ctx context.Context, in *DeleteFunctionRequest, opts ...grpc.CallOption) (*DeleteFunctionResponse, error)) *MockFunctionServiceClient_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockFunctionServiceClient
func (_mock *MockFunctionServiceClient) Get(ctx context.Context, in *GetFunctionRequest, opts ...grpc.CallOption) (*GetFunctionResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *GetFunctionResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *GetFunctionRequest, ...grpc.CallOption) (*GetFunctionResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *GetFunctionRequest, ...grpc.CallOption) *GetFunctionResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*GetFunctionResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *GetFunctionRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFunctionServiceClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockFunctionServiceClient_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - in *GetFunctionRequest
//   - opts ...grpc.CallOption
func (_e *MockFunctionServiceClient_Expecter) Get(ctx interface{}, in interface{}, opts ...interface{}) *MockFunctionServiceClient_Get_Call {
	return &MockFunctionServiceClient_Get_Call{Call: _e.mock.On("Get",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockFunctionServiceClient_Get_Call) Run(run func(ctx context.Context, in *GetFunctionRequest, opts ...grpc.CallOption)) *MockFunctionServiceClient_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *GetFunctionRequest
		if args[1] != nil {
			arg1 = args[1].(*GetFunctionRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockFunctionServiceClient_Get_Call) Return(getFunctionResponse *GetFunctionResponse, err error) *MockFunctionServiceClient_Get_Call {
	_c.Call.Return(getFunctionResponse, err)
	return _c
}

func (_c *MockFunctionServiceClient_Get_Call) RunAndReturn(run func(ctx context.Context, in *GetFunctionRequest, opts ...grpc.CallOption) (*GetFunctionResponse, error)) *MockFunctionServiceClient_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetLogs provides a mock function for the type MockFunctionServiceClient
func (_mock *MockFunctionServiceClient) GetLogs(ctx context.Context, in *GetFunctionLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEntry], error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetLogs")
	}

	var r0 grpc.ServerStreamingClient[LogEntry]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *GetFunctionLogsRequest, ...grpc.CallOption) (grpc.ServerStreamingClient[LogEntry], error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *GetFunctionLogsRequest, ...grpc.CallOption) grpc.ServerStreamingClient[LogEntry]); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(grpc.ServerStreamingClient[LogEntry])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *GetFunctionLogsRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFunctionServiceClient_GetLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLogs'
type MockFunctionServiceClient_GetLogs_Call struct {
	*mock.Call
}

// GetLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - in *GetFunctionLogsRequest
//   - opts ...grpc.CallOption
func (_e *MockFunctionServiceClient_Expecter) GetLogs(ctx interface{}, in interface{}, opts ...interface{}) *MockFunctionServiceClient_GetLogs_Call {
	return &MockFunctionServiceClient_GetLogs_Call{Call: _e.mock.On("GetLogs",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockFunctionServiceClient_GetLogs_Call) Run(run func(ctx context.Context, in *GetFunctionLogsRequest, opts ...grpc.CallOption)) *MockFunctionServiceClient_GetLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *GetFunctionLogsRequest
		if args[1] != nil {
			arg1 = args[1].(*GetFunctionLogsRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockFunctionServiceClient_GetLogs_Call) Return(serverStreamingClient grpc.ServerStreamingClient[LogEntry], err error) *MockFunctionServiceClient_GetLogs_Call {
	_c.Call.Return(serverStreamingClient, err)
	return _c
}

func (_c *MockFunctionServiceClient_GetLogs_Call) RunAndReturn(run func(ctx context.Context, in *GetFunctionLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEntry], error)) *MockFunctionServiceClient_GetLogs_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockFunctionServiceClient
func (_mock *MockFunctionServiceClient) List(ctx context.Context, in *ListFunctionsRequest, opts ...grpc.CallOption) (*ListFunctionsResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *ListFunctionsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ListFunctionsRequest, ...grpc.CallOption) (*ListFunctionsResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ListFunctionsRequest, ...grpc.CallOption) *ListFunctionsResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ListFunctionsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *ListFunctionsRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFunctionServiceClient_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockFunctionServiceClient_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - in *ListFunctionsRequest
//   - opts ...grpc.CallOption
func (_e *MockFunctionServiceClient_Expecter) List(ctx interface{}, in interface{}, opts ...interface{}) *MockFunctionServiceClient_List_Call {
	return &MockFunctionServiceClient_List_Call{Call: _e.mock.On("List",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockFunctionServiceClient_List_Call) Run(run func(ctx context.Context, in *ListFunctionsRequest, opts ...grpc.CallOption)) *MockFunctionServiceClient_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ListFunctionsRequest
		if args[1] != nil {
			arg1 = args[1].(*ListFunctionsRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockFunctionServiceClient_List_Call) Return(listFunctionsResponse *ListFunctionsResponse, err error) *MockFunctionServiceClient_List_Call {
	_c.Call.Return(listFunctionsResponse, err)
	return _c
}

func (_c *MockFunctionServiceClient_List_Call) RunAndReturn(run func(ctx context.Context, in *ListFunctionsRequest, opts ...grpc.CallOption) (*ListFunctionsResponse, error)) *MockFunctionServiceClient_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockFunctionServiceClient
func (_mock *MockFunctionServiceClient) Update(ctx context.Context, in *UpdateFunctionRequest, opts ...grpc.CallOption) (*UpdateFunctionResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *UpdateFunctionResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *UpdateFunctionRequest, ...grpc.CallOption) (*UpdateFunctionResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *UpdateFunctionRequest, ...grpc.CallOption) *UpdateFunctionResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*UpdateFunctionResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *UpdateFunctionRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFunctionServiceClient_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockFunctionServiceClient_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - in *UpdateFunctionRequest
//   - opts ...grpc.CallOption
func (_e *MockFunctionServiceClient_Expecter) Update(ctx interface{}, in interface{}, opts ...interface{}) *MockFunctionServiceClient_Update_Call {
	return &MockFunctionServiceClient_Update_Call{Call: _e.mock.On("Update",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockFunctionServiceClient_Update_Call) Run(run func(ctx context.Context, in *UpdateFunctionRequest, opts ...grpc.CallOption)) *MockFunctionServiceClient_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *UpdateFunctionRequest
		if args[1] != nil {
			arg1 = args[1].(*UpdateFunctionRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockFunctionServiceClient_Update_Call) Return(updateFunctionResponse *UpdateFunctionResponse, err error) *MockFunctionServiceClient_Update_Call {
	_c.Call.Return(updateFunctionResponse, err)
	return _c
}

func (_c *MockFunctionServiceClient_Update_Call) RunAndReturn(run func(ctx context.Context, in *UpdateFunctionRequest, opts ...grpc.CallOption) (*UpdateFunctionResponse, error)) *MockFunctionServiceClient_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFunctionService_GetLogsClient creates a new instance of MockFunctionService_GetLogsClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFunctionService_GetLogsClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFunctionService_GetLogsClient {
	mock := &MockFunctionService_GetLogsClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFunctionService_GetLogsClient is an autogenerated mock type for the FunctionService_GetLogsClient type
type MockFunctionService_GetLogsClient struct {
	mock.Mock
}

type MockFunctionService_GetLogsClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFunctionService_GetLogsClient) EXPECT() *MockFunctionService_GetLogsClient_Expecter {
	return &MockFunctionService_GetLogsClient_Expecter{mock: &_m.Mock}
}

// CloseSend provides a mock function for the type MockFunctionService_GetLogsClient
func (_mock *MockFunctionService_GetLogsClient) CloseSend() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CloseSend")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFunctionService_GetLogsClient_CloseSend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseSend'
type MockFunctionService_GetLogsClient_CloseSend_Call struct {
	*mock.Call
}

// CloseSend is a helper method to define mock.On call
func (_e *MockFunctionService_GetLogsClient_Expecter) CloseSend() *MockFunctionService_GetLogsClient_CloseSend_Call {
	return &MockFunctionService_GetLogsClient_CloseSend_Call{Call: _e.mock.On("CloseSend")}
}

func (_c *MockFunctionService_GetLogsClient_CloseSend_Call) Run(run func()) *MockFunctionService_GetLogsClient_CloseSend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFunctionService_GetLogsClient_CloseSend_Call) Return(err error) *MockFunctionService_GetLogsClient_CloseSend_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFunctionService_GetLogsClient_CloseSend_Call) RunAndReturn(run func() error) *MockFunctionService_GetLogsClient_CloseSend_Call {
	_c.Call.Return(run)
	return _c
}

// Context provides a mock function for the type MockFunctionService_GetLogsClient
func (_mock *MockFunctionService_GetLogsClient) Context() context.Context {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 context.Context
	if returnFunc, ok := ret.Get(0).(func() context.Context); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}
	return r0
}

// MockFunctionService_GetLogsClient_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type MockFunctionService_GetLogsClient_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *MockFunctionService_GetLogsClient_Expecter) Context() *MockFunctionService_GetLogsClient_Context_Call {
	return &MockFunctionService_GetLogsClient_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *MockFunctionService_GetLogsClient_Context_Call) Run(run func()) *MockFunctionService_GetLogsClient_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFunctionService_GetLogsClient_Context_Call) Return(context1 context.Context) *MockFunctionService_GetLogsClient_Context_Call {
	_c.Call.Return(context1)
	return _c
}

func (_c *MockFunctionService_GetLogsClient_Context_Call) RunAndReturn(run func() context.Context) *MockFunctionService_GetLogsClient_Context_Call {
	_c.Call.Return(run)
	return _c
}

// Header provides a mock function for the type MockFunctionService_GetLogsClient
func (_mock *MockFunctionService_GetLogsClient) Header() (metadata.MD, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Header")
	}

	var r0 metadata.MD
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (metadata.MD, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() metadata.MD); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(metadata.MD)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFunctionService_GetLogsClient_Header_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Header'
type MockFunctionService_GetLogsClient_Header_Call struct {
	*mock.Call
}

// Header is a helper method to define mock.On call
func (_e *MockFunctionService_GetLogsClient_Expecter) Header() *MockFunctionService_GetLogsClient_Header_Call {
	return &MockFunctionService_GetLogsClient_Header_Call{Call: _e.mock.On("Header")}
}

func (_c *MockFunctionService_GetLogsClient_Header_Call) Run(run func()) *MockFunctionService_GetLogsClient_Header_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFunctionService_GetLogsClient_Header_Call) Return(mD metadata.MD, err error) *MockFunctionService_GetLogsClient_Header_Call {
	_c.Call.Return(mD, err)
	return _c
}

func (_c *MockFunctionService_GetLogsClient_Header_Call) RunAndReturn(run func() (metadata.MD, error)) *MockFunctionService_GetLogsClient_Header_Call {
	_c.Call.Return(run)
	return _c
}

// Recv provides a mock function for the type MockFunctionService_GetLogsClient
func (_mock *MockFunctionService_GetLogsClient) Recv() (*LogEntry, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Recv")
	}

	var r0 *LogEntry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*LogEntry, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *LogEntry); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*LogEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFunctionService_GetLogsClient_Recv_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Recv'
type MockFunctionService_GetLogsClient_Recv_Call struct {
	*mock.Call
}

// Recv is a helper method to define mock.On call
func (_e *MockFunctionService_GetLogsClient_Expecter) Recv() *MockFunctionService_GetLogsClient_Recv_Call {
	return &MockFunctionService_GetLogsClient_Recv_Call{Call: _e.mock.On("Recv")}
}

func (_c *MockFunctionService_GetLogsClient_Recv_Call) Run(run func()) *MockFunctionService_GetLogsClient_Recv_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFunctionService_GetLogsClient_Recv_Call) Return(logEntry *LogEntry, err error) *MockFunctionService_GetLogsClient_Recv_Call {
	_c.Call.Return(logEntry, err)
	return _c
}

func (_c *MockFunctionService_GetLogsClient_Recv_Call) RunAndReturn(run func() (*LogEntry, error)) *MockFunctionService_GetLogsClient_Recv_Call {
	_c.Call.Return(run)
	return _c
}

// RecvMsg provides a mock function for the type MockFunctionService_GetLogsClient
func (_mock *MockFunctionService_GetLogsClient) RecvMsg(m any) error {
	ret := _mock.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for RecvMsg")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(any) error); ok {
		r0 = returnFunc(m)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFunctionService_GetLogsClient_RecvMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecvMsg'
type MockFunctionService_GetLogsClient_RecvMsg_Call struct {
	*mock.Call
}

// RecvMsg is a helper method to define mock.On call
//   - m any
func (_e *MockFunctionService_GetLogsClient_Expecter) RecvMsg(m interface{}) *MockFunctionService_GetLogsClient_RecvMsg_Call {
	return &MockFunctionService_GetLogsClient_RecvMsg_Call{Call: _e.mock.On("RecvMsg", m)}
}

func (_c *MockFunctionService_GetLogsClient_RecvMsg_Call) Run(run func(m any)) *MockFunctionService_GetLogsClient_RecvMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFunctionService_GetLogsClient_RecvMsg_Call) Return(err error) *MockFunctionService_GetLogsClient_RecvMsg_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFunctionService_GetLogsClient_RecvMsg_Call) RunAndReturn(run func(m any) error) *MockFunctionService_GetLogsClient_RecvMsg_Call {
	_c.Call.Return(run)
	return _c
}

// SendMsg provides a mock function for the type MockFunctionService_GetLogsClient
func (_mock *MockFunctionService_GetLogsClient) SendMsg(m any) error {
	ret := _mock.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for SendMsg")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(any) error); ok {
		r0 = returnFunc(m)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFunctionService_GetLogsClient_SendMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMsg'
type MockFunctionService_GetLogsClient_SendMsg_Call struct {
	*mock.Call
}

// SendMsg is a helper method to define mock.On call
//   - m any
func (_e *MockFunctionService_GetLogsClient_Expecter) SendMsg(m interface{}) *MockFunctionService_GetLogsClient_SendMsg_Call {
	return &MockFunctionService_GetLogsClient_SendMsg_Call{Call: _e.mock.On("SendMsg", m)}
}

func (_c *MockFunctionService_GetLogsClient_SendMsg_Call) Run(run func(m any)) *MockFunctionService_GetLogsClient_SendMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFunctionService_GetLogsClient_SendMsg_Call) Return(err error) *MockFunctionService_GetLogsClient_SendMsg_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFunctionService_GetLogsClient_SendMsg_Call) RunAndReturn(run func(m any) error) *MockFunctionService_GetLogsClient_SendMsg_Call {
	_c.Call.Return(run)
	return _c
}

// Trailer provides a mock function for the type MockFunctionService_GetLogsClient
func (_mock *MockFunctionService_GetLogsClient) Trailer() metadata.MD {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Trailer")
	}

	var r0 metadata.MD
	if returnFunc, ok := ret.Get(0).(func() metadata.MD); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(metadata.MD)
		}
	}
	return r0
}

// MockFunctionService_GetLogsClient_Trailer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Trailer'
type MockFunctionService_GetLogsClient_Trailer_Call struct {
	*mock.Call
}

// Trailer is a helper method to define mock.On call
func (_e *MockFunctionService_GetLogsClient_Expecter) Trailer() *MockFunctionService_GetLogsClient_Trailer_Call {
	return &MockFunctionService_GetLogsClient_Trailer_Call{Call: _e.mock.On("Trailer")}
}

func (_c *MockFunctionService_GetLogsClient_Trailer_Call) Run(run func()) *MockFunctionService_GetLogsClient_Trailer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFunctionService_GetLogsClient_Trailer_Call) Return(mD metadata.MD) *MockFunctionService_GetLogsClient_Trailer_Call {
	_c.Call.Return(mD)
	return _c
}

func (_c *MockFunctionService_GetLogsClient_Trailer_Call) RunAndReturn(run func() metadata.MD) *MockFunctionService_GetLogsClient_Trailer_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFunctionServiceServer creates a new instance of MockFunctionServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFunctionServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFunctionServiceServer {
	mock := &MockFunctionServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFunctionServiceServer is an autogenerated mock type for the FunctionServiceServer type
type MockFunctionServiceServer struct {
	mock.Mock
}

type MockFunctionServiceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFunctionServiceServer) EXPECT() *MockFunctionServiceServer_Expecter {
	return &MockFunctionServiceServer_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockFunctionServiceServer
func (_mock *MockFunctionServiceServer) Create(context1 context.Context, createFunctionRequest *CreateFunctionRequest) (*CreateFunctionResponse, error) {
	ret := _mock.Called(context1, createFunctionRequest)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *CreateFunctionResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *CreateFunctionRequest) (*CreateFunctionResponse, error)); ok {
		return returnFunc(context1, createFunctionRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *CreateFunctionRequest) *CreateFunctionResponse); ok {
		r0 = returnFunc(context1, createFunctionRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*CreateFunctionResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *CreateFunctionRequest) error); ok {
		r1 = returnFunc(context1, createFunctionRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFunctionServiceServer_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockFunctionServiceServer_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - context1 context.Context
//   - createFunctionRequest *CreateFunctionRequest
func (_e *MockFunctionServiceServer_Expecter) Create(context1 interface{}, createFunctionRequest interface{}) *MockFunctionServiceServer_Create_Call {
	return &MockFunctionServiceServer_Create_Call{Call: _e.mock.On("Create", context1, createFunctionRequest)}
}

func (_c *MockFunctionServiceServer_Create_Call) Run(run func(context1 context.Context, createFunctionRequest *CreateFunctionRequest)) *MockFunctionServiceServer_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *CreateFunctionRequest
		if args[1] != nil {
			arg1 = args[1].(*CreateFunctionRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFunctionServiceServer_Create_Call) Return(createFunctionResponse *CreateFunctionResponse, err error) *MockFunctionServiceServer_Create_Call {
	_c.Call.Return(createFunctionResponse, err)
	return _c
}

func (_c *MockFunctionServiceServer_Create_Call) RunAndReturn(run func(context1 context.Context, createFunctionRequest *CreateFunctionRequest) (*CreateFunctionResponse, error)) *MockFunctionServiceServer_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockFunctionServiceServer
func (_mock *MockFunctionServiceServer) Delete(context1 context.Context, deleteFunctionRequest *DeleteFunctionRequest) (*DeleteFunctionResponse, error) {
	ret := _mock.Called(context1, deleteFunctionRequest)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *DeleteFunctionResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *DeleteFunctionRequest) (*DeleteFunctionResponse, error)); ok {
		return returnFunc(context1, deleteFunctionRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *DeleteFunctionRequest) *DeleteFunctionResponse); ok {
		r0 = returnFunc(context1, deleteFunctionRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*DeleteFunctionResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *DeleteFunctionRequest) error); ok {
		r1 = returnFunc(context1, deleteFunctionRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFunctionServiceServer_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockFunctionServiceServer_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - context1 context.Context
//   - deleteFunctionRequest *DeleteFunctionRequest
func (_e *MockFunctionServiceServer_Expecter) Delete(context1 interface{}, deleteFunctionRequest interface{}) *MockFunctionServiceServer_Delete_Call {
	return &MockFunctionServiceServer_Delete_Call{Call: _e.mock.On("Delete", context1, deleteFunctionRequest)}
}

func (_c *MockFunctionServiceServer_Delete_Call) Run(run func(context1 context.Context, deleteFunctionRequest *DeleteFunctionRequest)) *MockFunctionServiceServer_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *DeleteFunctionRequest
		if args[1] != nil {
			arg1 = args[1].(*DeleteFunctionRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFunctionServiceServer_Delete_Call) Return(deleteFunctionResponse *DeleteFunctionResponse, err error) *MockFunctionServiceServer_Delete_Call {
	_c.Call.Return(deleteFunctionResponse, err)
	return _c
}

func (_c *MockFunctionServiceServer_Delete_Call) RunAndReturn(run func(context1 context.Context, deleteFunctionRequest *DeleteFunctionRequest) (*DeleteFunctionResponse, error)) *MockFunctionServiceServer_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockFunctionServiceServer
func (_mock *MockFunctionServiceServer) Get(context1 context.Context, getFunctionRequest *GetFunctionRequest) (*GetFunctionResponse, error) {
	ret := _mock.Called(context1, getFunctionRequest)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *GetFunctionResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *GetFunctionRequest) (*GetFunctionResponse, error)); ok {
		return returnFunc(context1, getFunctionRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *GetFunctionRequest) *GetFunctionResponse); ok {
		r0 = returnFunc(context1, getFunctionRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*GetFunctionResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *GetFunctionRequest) error); ok {
		r1 = returnFunc(context1, getFunctionRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFunctionServiceServer_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockFunctionServiceServer_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - context1 context.Context
//   - getFunctionRequest *GetFunctionRequest
func (_e *MockFunctionServiceServer_Expecter) Get(context1 interface{}, getFunctionRequest interface{}) *MockFunctionServiceServer_Get_Call {
	return &MockFunctionServiceServer_Get_Call{Call: _e.mock.On("Get", context1, getFunctionRequest)}
}

func (_c *MockFunctionServiceServer_Get_Call) Run(run func(context1 context.Context, getFunctionRequest *GetFunctionRequest)) *MockFunctionServiceServer_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *GetFunctionRequest
		if args[1] != nil {
			arg1 = args[1].(*GetFunctionRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFunctionServiceServer_Get_Call) Return(getFunctionResponse *GetFunctionResponse, err error) *MockFunctionServiceServer_Get_Call {
	_c.Call.Return(getFunctionResponse, err)
	return _c
}

func (_c *MockFunctionServiceServer_Get_Call) RunAndReturn(run func(context1 context.Context, getFunctionRequest *GetFunctionRequest) (*GetFunctionResponse, error)) *MockFunctionServiceServer_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetLogs provides a mock function for the type MockFunctionServiceServer
func (_mock *MockFunctionServiceServer) GetLogs(getFunctionLogsRequest *GetFunctionLogsRequest, serverStreamingServer grpc.ServerStreamingServer[LogEntry]) error {
	ret := _mock.Called(getFunctionLogsRequest, serverStreamingServer)

	if len(ret) == 0 {
		panic("no return value specified for GetLogs")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*GetFunctionLogsRequest, grpc.ServerStreamingServer[LogEntry]) error); ok {
		r0 = returnFunc(getFunctionLogsRequest, serverStreamingServer)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFunctionServiceServer_GetLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLogs'
type MockFunctionServiceServer_GetLogs_Call struct {
	*mock.Call
}

// GetLogs is a helper method to define mock.On call
//   - getFunctionLogsRequest *GetFunctionLogsRequest
//   - serverStreamingServer grpc.ServerStreamingServer[LogEntry]
func (_e *MockFunctionServiceServer_Expecter) GetLogs(getFunctionLogsRequest interface{}, serverStreamingServer interface{}) *MockFunctionServiceServer_GetLogs_Call {
	return &MockFunctionServiceServer_GetLogs_Call{Call: _e.mock.On("GetLogs", getFunctionLogsRequest, serverStreamingServer)}
}

func (_c *MockFunctionServiceServer_GetLogs_Call) Run(run func(getFunctionLogsRequest *GetFunctionLogsRequest, serverStreamingServer grpc.ServerStreamingServer[LogEntry])) *MockFunctionServiceServer_GetLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *GetFunctionLogsRequest
		if args[0] != nil {
			arg0 = args[0].(*GetFunctionLogsRequest)
		}
		var arg1 grpc.ServerStreamingServer[LogEntry]
		if args[1] != nil {
			arg1 = args[1].(grpc.ServerStreamingServer[LogEntry])
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFunctionServiceServer_GetLogs_Call) Return(err error) *MockFunctionServiceServer_GetLogs_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFunctionServiceServer_GetLogs_Call) RunAndReturn(run func(getFunctionLogsRequest *GetFunctionLogsRequest, serverStreamingServer grpc.ServerStreamingServer[LogEntry]) error) *MockFunctionServiceServer_GetLogs_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockFunctionServiceServer
func (_mock *MockFunctionServiceServer) List(context1 context.Context, listFunctionsRequest *ListFunctionsRequest) (*ListFunctionsResponse, error) {
	ret := _mock.Called(context1, listFunctionsRequest)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *ListFunctionsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ListFunctionsRequest) (*ListFunctionsResponse, error)); ok {
		return returnFunc(context1, listFunctionsRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ListFunctionsRequest) *ListFunctionsResponse); ok {
		r0 = returnFunc(context1, listFunctionsRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ListFunctionsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *ListFunctionsRequest) error); ok {
		r1 = returnFunc(context1, listFunctionsRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFunctionServiceServer_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockFunctionServiceServer_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - context1 context.Context
//   - listFunctionsRequest *ListFunctionsRequest
func (_e *MockFunctionServiceServer_Expecter) List(context1 interface{}, listFunctionsRequest interface{}) *MockFunctionServiceServer_List_Call {
	return &MockFunctionServiceServer_List_Call{Call: _e.mock.On("List", context1, listFunctionsRequest)}
}

func (_c *MockFunctionServiceServer_List_Call) Run(run func(context1 context.Context, listFunctionsRequest *ListFunctionsRequest)) *MockFunctionServiceServer_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ListFunctionsRequest
		if args[1] != nil {
			arg1 = args[1].(*ListFunctionsRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFunctionServiceServer_List_Call) Return(listFunctionsResponse *ListFunctionsResponse, err error) *MockFunctionServiceServer_List_Call {
	_c.Call.Return(listFunctionsResponse, err)
	return _c
}

func (_c *MockFunctionServiceServer_List_Call) RunAndReturn(run func(context1 context.Context, listFunctionsRequest *ListFunctionsRequest) (*ListFunctionsResponse, error)) *MockFunctionServiceServer_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockFunctionServiceServer
func (_mock *MockFunctionServiceServer) Update(context1 context.Context, updateFunctionRequest *UpdateFunctionRequest) (*UpdateFunctionResponse, error) {
	ret := _mock.Called(context1, updateFunctionRequest)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *UpdateFunctionResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *UpdateFunctionRequest) (*UpdateFunctionResponse, error)); ok {
		return returnFunc(context1, updateFunctionRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *UpdateFunctionRequest) *UpdateFunctionResponse); ok {
		r0 = returnFunc(context1, updateFunctionRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*UpdateFunctionResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *UpdateFunctionRequest) error); ok {
		r1 = returnFunc(context1, updateFunctionRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFunctionServiceServer_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockFunctionServiceServer_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - context1 context.Context
//   - updateFunctionRequest *UpdateFunctionRequest
func (_e *MockFunctionServiceServer_Expecter) Update(context1 interface{}, updateFunctionRequest interface{}) *MockFunctionServiceServer_Update_Call {
	return &MockFunctionServiceServer_Update_Call{Call: _e.mock.On("Update", context1, updateFunctionRequest)}
}

func (_c *MockFunctionServiceServer_Update_Call) Run(run func(context1 context.Context, updateFunctionRequest *UpdateFunctionRequest)) *MockFunctionServiceServer_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *UpdateFunctionRequest
		if args[1] != nil {
			arg1 = args[1].(*UpdateFunctionRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFunctionServiceServer_Update_Call) Return(updateFunctionResponse *UpdateFunctionResponse, err error) *MockFunctionServiceServer_Update_Call {
	_c.Call.Return(updateFunctionResponse, err)
	return _c
}

func (_c *MockFunctionServiceServer_Update_Call) RunAndReturn(run func(context1 context.Context, updateFunctionRequest *UpdateFunctionRequest) (*UpdateFunctionResponse, error)) *MockFunctionServiceServer_Update_Call {
	_c.Call.Return(run)
	return _c
}

// mustEmbedUnimplementedFunctionServiceServer provides a mock function for the type MockFunctionServiceServer
func (_mock *MockFunctionServiceServer) mustEmbedUnimplementedFunctionServiceServer() {
	_mock.Called()
	return
}

// MockFunctionServiceServer_mustEmbedUnimplementedFunctionServiceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedFunctionServiceServer'
type MockFunctionServiceServer_mustEmbedUnimplementedFunctionServiceServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedFunctionServiceServer is a helper method to define mock.On call
func (_e *MockFunctionServiceServer_Expecter) mustEmbedUnimplementedFunctionServiceServer() *MockFunctionServiceServer_mustEmbedUnimplementedFunctionServiceServer_Call {
	return &MockFunctionServiceServer_mustEmbedUnimplementedFunctionServiceServer_Call{Call: _e.mock.On("mustEmbedUnimplementedFunctionServiceServer")}
}

func (_c *MockFunctionServiceServer_mustEmbedUnimplementedFunctionServiceServer_Call) Run(run func()) *MockFunctionServiceServer_mustEmbedUnimplementedFunctionServiceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFunctionServiceServer_mustEmbedUnimplementedFunctionServiceServer_Call) Return() *MockFunctionServiceServer_mustEmbedUnimplementedFunctionServiceServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockFunctionServiceServer_mustEmbedUnimplementedFunctionServiceServer_Call) RunAndReturn(run func()) *MockFunctionServiceServer_mustEmbedUnimplementedFunctionServiceServer_Call {
	_c.Run(run)
	return _c
}

// NewMockUnsafeFunctionServiceServer creates a new instance of MockUnsafeFunctionServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUnsafeFunctionServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUnsafeFunctionServiceServer {
	mock := &MockUnsafeFunctionServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUnsafeFunctionServiceServer is an autogenerated mock type for the UnsafeFunctionServiceServer type
type MockUnsafeFunctionServiceServer struct {
	mock.Mock
}

type MockUnsafeFunctionServiceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUnsafeFunctionServiceServer) EXPECT() *MockUnsafeFunctionServiceServer_Expecter {
	return &MockUnsafeFunctionServiceServer_Expecter{mock: &_m.Mock}
}

// mustEmbedUnimplementedFunctionServiceServer provides a mock function for the type MockUnsafeFunctionServiceServer
func (_mock *MockUnsafeFunctionServiceServer) mustEmbedUnimplementedFunctionServiceServer() {
	_mock.Called()
	return
}

// MockUnsafeFunctionServiceServer_mustEmbedUnimplementedFunctionServiceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedFunctionServiceServer'
type MockUnsafeFunctionServiceServer_mustEmbedUnimplementedFunctionServiceServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedFunctionServiceServer is a helper method to define mock.On call
func (_e *MockUnsafeFunctionServiceServer_Expecter) mustEmbedUnimplementedFunctionServiceServer() *MockUnsafeFunctionServiceServer_mustEmbedUnimplementedFunctionServiceServer_Call {
	return &MockUnsafeFunctionServiceServer_mustEmbedUnimplementedFunctionServiceServer_Call{Call: _e.mock.On("mustEmbedUnimplementedFunctionServiceServer")}
}

func (_c *MockUnsafeFunctionServiceServer_mustEmbedUnimplementedFunctionServiceServer_Call) Run(run func()) *MockUnsafeFunctionServiceServer_mustEmbedUnimplementedFunctionServiceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUnsafeFunctionServiceServer_mustEmbedUnimplementedFunctionServiceServer_Call) Return() *MockUnsafeFunctionServiceServer_mustEmbedUnimplementedFunctionServiceServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockUnsafeFunctionServiceServer_mustEmbedUnimplementedFunctionServiceServer_Call) RunAndReturn(run func()) *MockUnsafeFunctionServiceServer_mustEmbedUnimplementedFunctionServiceServer_Call {
	_c.Run(run)
	return _c
}

// NewMockFunctionService_GetLogsServer creates a new instance of MockFunctionService_GetLogsServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFunctionService_GetLogsServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFunctionService_GetLogsServer {
	mock := &MockFunctionService_GetLogsServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFunctionService_GetLogsServer is an autogenerated mock type for the FunctionService_GetLogsServer type
type MockFunctionService_GetLogsServer struct {
	mock.Mock
}

type MockFunctionService_GetLogsServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFunctionService_GetLogsServer) EXPECT() *MockFunctionService_GetLogsServer_Expecter {
	return &MockFunctionService_GetLogsServer_Expecter{mock: &_m.Mock}
}

// Context provides a mock function for the type MockFunctionService_GetLogsServer
func (_mock *MockFunctionService_GetLogsServer) Context() context.Context {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 context.Context
	if returnFunc, ok := ret.Get(0).(func() context.Context); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}
	return r0
}

// MockFunctionService_GetLogsServer_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type MockFunctionService_GetLogsServer_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *MockFunctionService_GetLogsServer_Expecter) Context() *MockFunctionService_GetLogsServer_Context_Call {
	return &MockFunctionService_GetLogsServer_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *MockFunctionService_GetLogsServer_Context_Call) Run(run func()) *MockFunctionService_GetLogsServer_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFunctionService_GetLogsServer_Context_Call) Return(context1 context.Context) *MockFunctionService_GetLogsServer_Context_Call {
	_c.Call.Return(context1)
	return _c
}

func (_c *MockFunctionService_GetLogsServer_Context_Call) RunAndReturn(run func() context.Context) *MockFunctionService_GetLogsServer_Context_Call {
	_c.Call.Return(run)
	return _c
}

// RecvMsg provides a mock function for the type MockFunctionService_GetLogsServer
func (_mock *MockFunctionService_GetLogsServer) RecvMsg(m any) error {
	ret := _mock.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for RecvMsg")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(any) error); ok {
		r0 = returnFunc(m)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFunctionService_GetLogsServer_RecvMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecvMsg'
type MockFunctionService_GetLogsServer_RecvMsg_Call struct {
	*mock.Call
}

// RecvMsg is a helper method to define mock.On call
//   - m any
func (_e *MockFunctionService_GetLogsServer_Expecter) RecvMsg(m interface{}) *MockFunctionService_GetLogsServer_RecvMsg_Call {
	return &MockFunctionService_GetLogsServer_RecvMsg_Call{Call: _e.mock.On("RecvMsg", m)}
}

func (_c *MockFunctionService_GetLogsServer_RecvMsg_Call) Run(run func(m any)) *MockFunctionService_GetLogsServer_RecvMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFunctionService_GetLogsServer_RecvMsg_Call) Return(err error) *MockFunctionService_GetLogsServer_RecvMsg_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFunctionService_GetLogsServer_RecvMsg_Call) RunAndReturn(run func(m any) error) *MockFunctionService_GetLogsServer_RecvMsg_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function for the type MockFunctionService_GetLogsServer
func (_mock *MockFunctionService_GetLogsServer) Send(logEntry *LogEntry) error {
	ret := _mock.Called(logEntry)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*LogEntry) error); ok {
		r0 = returnFunc(logEntry)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFunctionService_GetLogsServer_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockFunctionService_GetLogsServer_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - logEntry *LogEntry
func (_e *MockFunctionService_GetLogsServer_Expecter) Send(logEntry interface{}) *MockFunctionService_GetLogsServer_Send_Call {
	return &MockFunctionService_GetLogsServer_Send_Call{Call: _e.mock.On("Send", logEntry)}
}

func (_c *MockFunctionService_GetLogsServer_Send_Call) Run(run func(logEntry *LogEntry)) *MockFunctionService_GetLogsServer_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *LogEntry
		if args[0] != nil {
			arg0 = args[0].(*LogEntry)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFunctionService_GetLogsServer_Send_Call) Return(err error) *MockFunctionService_GetLogsServer_Send_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFunctionService_GetLogsServer_Send_Call) RunAndReturn(run func(logEntry *LogEntry) error) *MockFunctionService_GetLogsServer_Send_Call {
	_c.Call.Return(run)
	return _c
}

// SendHeader provides a mock function for the type MockFunctionService_GetLogsServer
func (_mock *MockFunctionService_GetLogsServer) SendHeader(mD metadata.MD) error {
	ret := _mock.Called(mD)

	if len(ret) == 0 {
		panic("no return value specified for SendHeader")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(metadata.MD) error); ok {
		r0 = returnFunc(mD)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFunctionService_GetLogsServer_SendHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendHeader'
type MockFunctionService_GetLogsServer_SendHeader_Call struct {
	*mock.Call
}

// SendHeader is a helper method to define mock.On call
//   - mD metadata.MD
func (_e *MockFunctionService_GetLogsServer_Expecter) SendHeader(mD interface{}) *MockFunctionService_GetLogsServer_SendHeader_Call {
	return &MockFunctionService_GetLogsServer_SendHeader_Call{Call: _e.mock.On("SendHeader", mD)}
}

func (_c *MockFunctionService_GetLogsServer_SendHeader_Call) Run(run func(mD metadata.MD)) *MockFunctionService_GetLogsServer_SendHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 metadata.MD
		if args[0] != nil {
			arg0 = args[0].(metadata.MD)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFunctionService_GetLogsServer_SendHeader_Call) Return(err error) *MockFunctionService_GetLogsServer_SendHeader_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFunctionService_GetLogsServer_SendHeader_Call) RunAndReturn(run func(mD metadata.MD) error) *MockFunctionService_GetLogsServer_SendHeader_Call {
	_c.Call.Return(run)
	return _c
}

// SendMsg provides a mock function for the type MockFunctionService_GetLogsServer
func (_mock *MockFunctionService_GetLogsServer) SendMsg(m any) error {
	ret := _mock.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for SendMsg")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(any) error); ok {
		r0 = returnFunc(m)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFunctionService_GetLogsServer_SendMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMsg'
type MockFunctionService_GetLogsServer_SendMsg_Call struct {
	*mock.Call
}

// SendMsg is a helper method to define mock.On call
//   - m any
func (_e *MockFunctionService_GetLogsServer_Expecter) SendMsg(m interface{}) *MockFunctionService_GetLogsServer_SendMsg_Call {
	return &MockFunctionService_GetLogsServer_SendMsg_Call{Call: _e.mock.On("SendMsg", m)}
}

func (_c *MockFunctionService_GetLogsServer_SendMsg_Call) Run(run func(m any)) *MockFunctionService_GetLogsServer_SendMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFunctionService_GetLogsServer_SendMsg_Call) Return(err error) *MockFunctionService_GetLogsServer_SendMsg_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFunctionService_GetLogsServer_SendMsg_Call) RunAndReturn(run func(m any) error) *MockFunctionService_GetLogsServer_SendMsg_Call {
	_c.Call.Return(run)
	return _c
}

// SetHeader provides a mock function for the type MockFunctionService_GetLogsServer
func (_mock *MockFunctionService_GetLogsServer) SetHeader(mD metadata.MD) error {
	ret := _mock.Called(mD)

	if len(ret) == 0 {
		panic("no return value specified for SetHeader")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(metadata.MD) error); ok {
		r0 = returnFunc(mD)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFunctionService_GetLogsServer_SetHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHeader'
type MockFunctionService_GetLogsServer_SetHeader_Call struct {
	*mock.Call
}

// SetHeader is a helper method to define mock.On call
//   - mD metadata.MD
func (_e *MockFunctionService_GetLogsServer_Expecter) SetHeader(mD interface{}) *MockFunctionService_GetLogsServer_SetHeader_Call {
	return &MockFunctionService_GetLogsServer_SetHeader_Call{Call: _e.mock.On("SetHeader", mD)}
}

func (_c *MockFunctionService_GetLogsServer_SetHeader_Call) Run(run func(mD metadata.MD)) *MockFunctionService_GetLogsServer_SetHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 metadata.MD
		if args[0] != nil {
			arg0 = args[0].(metadata.MD)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFunctionService_GetLogsServer_SetHeader_Call) Return(err error) *MockFunctionService_GetLogsServer_SetHeader_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFunctionService_GetLogsServer_SetHeader_Call) RunAndReturn(run func(mD metadata.MD) error) *MockFunctionService_GetLogsServer_SetHeader_Call {
	_c.Call.Return(run)
	return _c
}

// SetTrailer provides a mock function for the type MockFunctionService_GetLogsServer
func (_mock *MockFunctionService_GetLogsServer) SetTrailer(mD metadata.MD) {
	_mock.Called(mD)
	return
}

// MockFunctionService_GetLogsServer_SetTrailer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTrailer'
type MockFunctionService_GetLogsServer_SetTrailer_Call struct {
	*mock.Call
}

// SetTrailer is a helper method to define mock.On call
//   - mD metadata.MD
func (_e *MockFunctionService_GetLogsServer_Expecter) SetTrailer(mD interface{}) *MockFunctionService_GetLogsServer_SetTrailer_Call {
	return &MockFunctionService_GetLogsServer_SetTrailer_Call{Call: _e.mock.On("SetTrailer", mD)}
}

func (_c *MockFunctionService_GetLogsServer_SetTrailer_Call) Run(run func(mD metadata.MD)) *MockFunctionService_GetLogsServer_SetTrailer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 metadata.MD
		if args[0] != nil {
			arg0 = args[0].(metadata.MD)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFunctionService_GetLogsServer_SetTrailer_Call) Return() *MockFunctionService_GetLogsServer_SetTrailer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockFunctionService_GetLogsServer_SetTrailer_Call) RunAndReturn(run func(mD metadata.MD)) *MockFunctionService_GetLogsServer_SetTrailer_Call {
	_c.Run(run)
	return _c
}
