grpc_server:
  host: 0.0.0.0
  port: 20000
http_server:
  host: 0.0.0.0
  port: 8080
  admin_host: 0.0.0.0
  admin_port: 8081
observability:
  service:
    name: control-plane
    version: dev
    environment: local
  tracing:
    enabled: false
  metrics:
    enabled: true
log:
  level: info
  encoding: json
